name = "Pick 'n' Mix"
author = "Squash"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "346c287add4e08914b7315a81989ee7073cb6a46c2efc3e22d84a0f3ec18b6a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
