name = "Pick 'n' Mix"
author = "Squash"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45b457a91633da37eb2fc510022f680cb9d458815d40de06039eb2c5e5644b19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
