name = "Pick 'n' Mix"
author = "Squash"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc110a80b6840808ede0a48e92236292adc679c598c5ffcd8afe3d30e3a57f09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
